### ISSUE TITLE
Garmin does not recognise this MapShare Identifier

### ISSUE THREAD

**Issue by Lastone17** [morehawes/inreach-mapshare#2]
Hi,
I want to use your plugin but I am getting the following errors:
[Info] https://explore.garmin.com/feed/share/xxx(request_ready)
[Error] Garmin does not recognise this MapShare Identifier. (identifier)
[Error] Garmin provided an empty response. Check your MapShare Settings. (empty_response)

But I can download the feeds by hand, they are working perfectly fine. what I am doing wrong?

**Comment by morehawes** [comment]
Hi @Lastone17,

Sorry to hear you have been experiencing issues. This is quite hard to diagnose without an actually Mapshare Identifier. What device are you using? Have you double checked all settings?

Cheers,
Joe

**Comment by Lastone17** [comment]
Double checked everything. Identifier: sailingnebula
Does your plugin still works on wordpress websites?
Because of the garmin API you just get the data as attachment not as response body.

**Comment by morehawes** [comment]
Hi @Lastone17,

Thanks for the extra detail. 

> Does your plugin still works on wordpress websites?

It is definitely working for me, I just got back from a trip where I used it.

I just took a look using your identifier and I too am seeing unexpected results (i.e. a completely empty response):

https://explore.garmin.com/feed/share/morehawes (downloads most recent track point as KML)
vs
https://explore.garmin.com/feed/share/sailingnebula (completely empty response)

> Because of the garmin API you just get the data as attachment not as response body. Im using garmin inreach 2

> But I can download the feeds by hand

Could you elaborate on these? Are you able to provide any URLs?

I just recently found out that I have a "legacy" account, i.e. [supported by Roadpost instead of Garmin](https://support.roadpost.com/hc/en-us/articles/14128062909204-Is-my-inReach-Account-with-Garmin-or-Roadpost-) so my guess is that there lies the difference.

The only documentation I have seen is very out of date and the Explore Garmin portal is *the worst*. Perhaps you have a different portal?

If this is the case I will have to put up a message warning other users until I am able to test with the new Garmin system.

It's also possible that I am being dumb and missing something obvious. I appreciate any more information you can provide.

Cheers,

Joe

**Comment by Lastone17** [comment]
@morehawes it changed a bit I guess.
https://inreach.garmin.com/Feed/Share/Sailingnebula?d1=2023-07-16T10:00z&d2=2023-07-29T12:00z
if you test this URL you will get a response. (note the d1 & d2 provided). But with your plugin it doesn't seem to work.
You get the response as attachment, I don't know how your plugin handles this?
Documentation I got: https://support.garmin.com/en-US/?faq=tdlDCyo1fJ5UxjUbA9rMY8
If you scroll further down you get some more informations.

Would be awesome if we could use your plugin with the "new" API.

**Comment by morehawes** [comment]
Hi @Lastone17,

Thanks again for the extra detail, I really appreciate it as it would be great to get this figured out.

> https://inreach.garmin.com/Feed/Share/Sailingnebula?d1=2023-07-16T10:00z&d2=2023-07-29T12:00z OR https://explore.garmin.com/feed/share/sailingnebula?d1=2023-07-16T10:00z&d2=2023-07-29T12:00z

The first URL redirects to the second (explore.garmin.com/feed/share), so that seems to be the one to use.

> (note the d1 & d2 provided)

These are optional - leaving them off _should_ just download the most recent track point, so I'll ignore them for now to keep things simple.

> Documentation I got: https://support.garmin.com/en-US/?faq=tdlDCyo1fJ5UxjUbA9rMY8

Yes that's the only documentation I have been able to find also.

> You get the response as attachment, I don't know how your plugin handles this?

Yes, this is the expected behaviour. The plugin downloads the KML if triggered by the URL.

>  if you test this URL you will get a response.

I still get a completely empty response, same as before. Tested on multiple browsers/devices:

> https://explore.garmin.com/feed/share/morehawes (downloads most recent track point as KML)
> vs
> https://explore.garmin.com/feed/share/sailingnebula (completely empty response)

<img width="1097" alt="Screenshot 2023-07-29 at 8 01 25 AM" src="https://github.com/morehawes/inreach-mapshare/assets/1234034/7ebd2c40-ea15-4b49-8a2e-260f63db77a6">

Which is really weird if it is working for you :-/ The only thing I can think of is that you have a cookie or session data that is making it work for you but not me. Could you try your URL in a private/incognito browser window (i.e. a fresh browser window with cleared cookies/history) to see if you get the same results?

Thanks again.

**Comment by Lastone17** [comment]
@morehawes you are right, it also worked once. I also tested with postman no response for my mapshare whatsoever.
![image](https://github.com/morehawes/inreach-mapshare/assets/11078630/3af283db-89e0-49f9-8333-07aaf64fcce8)
But my settings should be alright, so it once worked for download, that's really weird.
Do you know any settings I should check?
If you check https://share.garmin.com/sailingnebula you will see the recent track, so it should work for the KML as well?

**Comment by morehawes** [comment]
Hi @Lastone17,

Bingo! It seems that they have changed the endpoint from:

https://inreach.garmin.com/feed/share/<MapShare Identifier>

to:

https://share.garmin.com/feed/share/<MapShare Identifier>

but did not update the [docs](https://support.garmin.com/en-US/?faq=tdlDCyo1fJ5UxjUbA9rMY8).

With the old endpoint working for my ("legacy") account but not yours.

Luckily the new endpoint seems to work for both, so I have updated that in version 1.2, available on the master branch.

Please let me know if you spot any more issues and many thanks for persevering to get this fixed! :0)

Cheers,

Joe

**Comment by Lastone17** [comment]
@morehawes still getting the same error
![image](https://github.com/morehawes/inreach-mapshare/assets/11078630/564ee01c-2ea0-4063-8da9-50681dee37a1)
Seems like it's not changed?
https://explore.garmin.com/feed/share/Sailingnebula -> **No response**
https://share.garmin.com/Feed/Share/Sailingnebula -> Response

**Comment by morehawes** [comment]
> On the installation it also still says Version 1.1 and not 1.2

My bad. Should be 1.2 now with the fix included. Please let me know how you get on.

Cheers,

Joe

**Comment by morehawes** [comment]
> it's working now thanks!

Great! :)

> Just on mobile it doesn't seem that responsive, but anyways good work! Fullscreen button from openstreetmap seems very buggy

Feel free to open a separate issue, ideally with a URL if you believe there is a bug.

Cheers,

Joe
